#!/bin/bash
# Vercel projekt ellenőrző és beállító script

echo "🔍 VERCEL PROJEKT BEÁLLÍTÁS ELLENŐRZŐ"
echo "======================================"
echo ""
echo "Kérlek ellenőrizd az alábbi dolgokat a Vercel Dashboard-on:"
echo ""
echo "1. PROJEKT KAPCSOLAT:"
echo "   - Menj: https://vercel.com/dashboard"
echo "   - Válaszd ki a CompanyIntel projektet"
echo "   - Settings → General"
echo "   - Nézd meg: van-e 'Git Repository' beállítva?"
echo ""
echo "   Ha NINCS Git Repository:"
echo "   ========================="
echo "   A projekt még nincs Git-hez csatlakoztatva!"
echo ""
echo "   MEGOLDÁS:"
echo "   1. Settings → General"
echo "   2. 'Connect Git Repository'"
echo "   3. Válaszd ki: ebastyan/CompanyIntel"
echo "   4. Branch: claude/fix-existing-issues-01XfBT11ep658MwdRcNR1YTQ"
echo ""
echo "   Ha VAN Git Repository:"
echo "   ======================"
echo "   2. Settings → Git"
echo "   3. Production Branch: claude/fix-existing-issues-01XfBT11ep658MwdRcNR1YTQ"
echo ""
echo "2. ALTERNATÍVA - VERCEL CLI:"
echo "   ============================"
echo "   npx vercel --prod"
echo ""
echo "3. ALTERNATÍVA - DEPLOY HOOK:"
echo "   ============================"
echo "   Hozz létre egy Deploy Hook-ot:"
echo "   - Settings → Git → Deploy Hooks"
echo "   - Hook name: claude-branch"
echo "   - Git Branch: claude/fix-existing-issues-01XfBT11ep658MwdRcNR1YTQ"
echo "   - Create Hook"
echo "   - Másold ki az URL-t és hívd meg: curl -X POST [URL]"
echo ""
